package org.itboys.trade.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.itboys.trade.entity.WeixinConfig;
import org.itboys.trade.entity.WeixinConfigExample;

public interface WeixinConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    int countByExample(WeixinConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    int deleteByExample(WeixinConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    int insert(WeixinConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    int insertSelective(WeixinConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    List<WeixinConfig> selectByExample(WeixinConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    WeixinConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WeixinConfig record, @Param("example") WeixinConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WeixinConfig record, @Param("example") WeixinConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WeixinConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WeixinConfig record);
}