package org.itboys.trade.entity;

import java.io.Serializable;
import java.util.Date;

public class WeixinConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.weixin_id
     *
     * @mbggenerated
     */
    private String weixinId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.weixin_no
     *
     * @mbggenerated
     */
    private String weixinNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.type
     *
     * @mbggenerated
     */
    private Boolean type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.logo
     *
     * @mbggenerated
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.ewm
     *
     * @mbggenerated
     */
    private String ewm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.app_secret
     *
     * @mbggenerated
     */
    private String appSecret;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.creator
     *
     * @mbggenerated
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.updater
     *
     * @mbggenerated
     */
    private Long updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.is_deleted
     *
     * @mbggenerated
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.project_id
     *
     * @mbggenerated
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.parent_id
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.partner_key
     *
     * @mbggenerated
     */
    private String partnerKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.site_domain
     *
     * @mbggenerated
     */
    private String siteDomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.reflect_bean
     *
     * @mbggenerated
     */
    private String reflectBean;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.reflect_method
     *
     * @mbggenerated
     */
    private String reflectMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.ewm1
     *
     * @mbggenerated
     */
    private String ewm1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.ewm2
     *
     * @mbggenerated
     */
    private String ewm2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.ewm3
     *
     * @mbggenerated
     */
    private String ewm3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.ewm4
     *
     * @mbggenerated
     */
    private String ewm4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.ewm5
     *
     * @mbggenerated
     */
    private String ewm5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.pay_sign_key
     *
     * @mbggenerated
     */
    private String paySignKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.partner_id
     *
     * @mbggenerated
     */
    private String partnerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.field1
     *
     * @mbggenerated
     */
    private String field1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.field2
     *
     * @mbggenerated
     */
    private String field2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.field3
     *
     * @mbggenerated
     */
    private String field3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.obj_id
     *
     * @mbggenerated
     */
    private Long objId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.obj_id1
     *
     * @mbggenerated
     */
    private Long objId1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_config.pass
     *
     * @mbggenerated
     */
    private Boolean pass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.id
     *
     * @return the value of weixin_config.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.id
     *
     * @param id the value for weixin_config.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.name
     *
     * @return the value of weixin_config.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.name
     *
     * @param name the value for weixin_config.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.email
     *
     * @return the value of weixin_config.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.email
     *
     * @param email the value for weixin_config.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.weixin_id
     *
     * @return the value of weixin_config.weixin_id
     *
     * @mbggenerated
     */
    public String getWeixinId() {
        return weixinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.weixin_id
     *
     * @param weixinId the value for weixin_config.weixin_id
     *
     * @mbggenerated
     */
    public void setWeixinId(String weixinId) {
        this.weixinId = weixinId == null ? null : weixinId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.weixin_no
     *
     * @return the value of weixin_config.weixin_no
     *
     * @mbggenerated
     */
    public String getWeixinNo() {
        return weixinNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.weixin_no
     *
     * @param weixinNo the value for weixin_config.weixin_no
     *
     * @mbggenerated
     */
    public void setWeixinNo(String weixinNo) {
        this.weixinNo = weixinNo == null ? null : weixinNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.type
     *
     * @return the value of weixin_config.type
     *
     * @mbggenerated
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.type
     *
     * @param type the value for weixin_config.type
     *
     * @mbggenerated
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.logo
     *
     * @return the value of weixin_config.logo
     *
     * @mbggenerated
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.logo
     *
     * @param logo the value for weixin_config.logo
     *
     * @mbggenerated
     */
    public void setLogo(String logo) {
        this.logo = logo == null ? null : logo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.ewm
     *
     * @return the value of weixin_config.ewm
     *
     * @mbggenerated
     */
    public String getEwm() {
        return ewm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.ewm
     *
     * @param ewm the value for weixin_config.ewm
     *
     * @mbggenerated
     */
    public void setEwm(String ewm) {
        this.ewm = ewm == null ? null : ewm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.app_id
     *
     * @return the value of weixin_config.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.app_id
     *
     * @param appId the value for weixin_config.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.app_secret
     *
     * @return the value of weixin_config.app_secret
     *
     * @mbggenerated
     */
    public String getAppSecret() {
        return appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.app_secret
     *
     * @param appSecret the value for weixin_config.app_secret
     *
     * @mbggenerated
     */
    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret == null ? null : appSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.token
     *
     * @return the value of weixin_config.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.token
     *
     * @param token the value for weixin_config.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.creator
     *
     * @return the value of weixin_config.creator
     *
     * @mbggenerated
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.creator
     *
     * @param creator the value for weixin_config.creator
     *
     * @mbggenerated
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.create_time
     *
     * @return the value of weixin_config.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.create_time
     *
     * @param createTime the value for weixin_config.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.updater
     *
     * @return the value of weixin_config.updater
     *
     * @mbggenerated
     */
    public Long getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.updater
     *
     * @param updater the value for weixin_config.updater
     *
     * @mbggenerated
     */
    public void setUpdater(Long updater) {
        this.updater = updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.update_time
     *
     * @return the value of weixin_config.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.update_time
     *
     * @param updateTime the value for weixin_config.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.is_deleted
     *
     * @return the value of weixin_config.is_deleted
     *
     * @mbggenerated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.is_deleted
     *
     * @param isDeleted the value for weixin_config.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.project_id
     *
     * @return the value of weixin_config.project_id
     *
     * @mbggenerated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.project_id
     *
     * @param projectId the value for weixin_config.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.parent_id
     *
     * @return the value of weixin_config.parent_id
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.parent_id
     *
     * @param parentId the value for weixin_config.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.partner_key
     *
     * @return the value of weixin_config.partner_key
     *
     * @mbggenerated
     */
    public String getPartnerKey() {
        return partnerKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.partner_key
     *
     * @param partnerKey the value for weixin_config.partner_key
     *
     * @mbggenerated
     */
    public void setPartnerKey(String partnerKey) {
        this.partnerKey = partnerKey == null ? null : partnerKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.site_domain
     *
     * @return the value of weixin_config.site_domain
     *
     * @mbggenerated
     */
    public String getSiteDomain() {
        return siteDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.site_domain
     *
     * @param siteDomain the value for weixin_config.site_domain
     *
     * @mbggenerated
     */
    public void setSiteDomain(String siteDomain) {
        this.siteDomain = siteDomain == null ? null : siteDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.reflect_bean
     *
     * @return the value of weixin_config.reflect_bean
     *
     * @mbggenerated
     */
    public String getReflectBean() {
        return reflectBean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.reflect_bean
     *
     * @param reflectBean the value for weixin_config.reflect_bean
     *
     * @mbggenerated
     */
    public void setReflectBean(String reflectBean) {
        this.reflectBean = reflectBean == null ? null : reflectBean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.reflect_method
     *
     * @return the value of weixin_config.reflect_method
     *
     * @mbggenerated
     */
    public String getReflectMethod() {
        return reflectMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.reflect_method
     *
     * @param reflectMethod the value for weixin_config.reflect_method
     *
     * @mbggenerated
     */
    public void setReflectMethod(String reflectMethod) {
        this.reflectMethod = reflectMethod == null ? null : reflectMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.ewm1
     *
     * @return the value of weixin_config.ewm1
     *
     * @mbggenerated
     */
    public String getEwm1() {
        return ewm1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.ewm1
     *
     * @param ewm1 the value for weixin_config.ewm1
     *
     * @mbggenerated
     */
    public void setEwm1(String ewm1) {
        this.ewm1 = ewm1 == null ? null : ewm1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.ewm2
     *
     * @return the value of weixin_config.ewm2
     *
     * @mbggenerated
     */
    public String getEwm2() {
        return ewm2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.ewm2
     *
     * @param ewm2 the value for weixin_config.ewm2
     *
     * @mbggenerated
     */
    public void setEwm2(String ewm2) {
        this.ewm2 = ewm2 == null ? null : ewm2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.ewm3
     *
     * @return the value of weixin_config.ewm3
     *
     * @mbggenerated
     */
    public String getEwm3() {
        return ewm3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.ewm3
     *
     * @param ewm3 the value for weixin_config.ewm3
     *
     * @mbggenerated
     */
    public void setEwm3(String ewm3) {
        this.ewm3 = ewm3 == null ? null : ewm3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.ewm4
     *
     * @return the value of weixin_config.ewm4
     *
     * @mbggenerated
     */
    public String getEwm4() {
        return ewm4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.ewm4
     *
     * @param ewm4 the value for weixin_config.ewm4
     *
     * @mbggenerated
     */
    public void setEwm4(String ewm4) {
        this.ewm4 = ewm4 == null ? null : ewm4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.ewm5
     *
     * @return the value of weixin_config.ewm5
     *
     * @mbggenerated
     */
    public String getEwm5() {
        return ewm5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.ewm5
     *
     * @param ewm5 the value for weixin_config.ewm5
     *
     * @mbggenerated
     */
    public void setEwm5(String ewm5) {
        this.ewm5 = ewm5 == null ? null : ewm5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.pay_sign_key
     *
     * @return the value of weixin_config.pay_sign_key
     *
     * @mbggenerated
     */
    public String getPaySignKey() {
        return paySignKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.pay_sign_key
     *
     * @param paySignKey the value for weixin_config.pay_sign_key
     *
     * @mbggenerated
     */
    public void setPaySignKey(String paySignKey) {
        this.paySignKey = paySignKey == null ? null : paySignKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.partner_id
     *
     * @return the value of weixin_config.partner_id
     *
     * @mbggenerated
     */
    public String getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.partner_id
     *
     * @param partnerId the value for weixin_config.partner_id
     *
     * @mbggenerated
     */
    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId == null ? null : partnerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.field1
     *
     * @return the value of weixin_config.field1
     *
     * @mbggenerated
     */
    public String getField1() {
        return field1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.field1
     *
     * @param field1 the value for weixin_config.field1
     *
     * @mbggenerated
     */
    public void setField1(String field1) {
        this.field1 = field1 == null ? null : field1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.field2
     *
     * @return the value of weixin_config.field2
     *
     * @mbggenerated
     */
    public String getField2() {
        return field2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.field2
     *
     * @param field2 the value for weixin_config.field2
     *
     * @mbggenerated
     */
    public void setField2(String field2) {
        this.field2 = field2 == null ? null : field2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.field3
     *
     * @return the value of weixin_config.field3
     *
     * @mbggenerated
     */
    public String getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.field3
     *
     * @param field3 the value for weixin_config.field3
     *
     * @mbggenerated
     */
    public void setField3(String field3) {
        this.field3 = field3 == null ? null : field3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.obj_id
     *
     * @return the value of weixin_config.obj_id
     *
     * @mbggenerated
     */
    public Long getObjId() {
        return objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.obj_id
     *
     * @param objId the value for weixin_config.obj_id
     *
     * @mbggenerated
     */
    public void setObjId(Long objId) {
        this.objId = objId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.obj_id1
     *
     * @return the value of weixin_config.obj_id1
     *
     * @mbggenerated
     */
    public Long getObjId1() {
        return objId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.obj_id1
     *
     * @param objId1 the value for weixin_config.obj_id1
     *
     * @mbggenerated
     */
    public void setObjId1(Long objId1) {
        this.objId1 = objId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_config.pass
     *
     * @return the value of weixin_config.pass
     *
     * @mbggenerated
     */
    public Boolean getPass() {
        return pass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_config.pass
     *
     * @param pass the value for weixin_config.pass
     *
     * @mbggenerated
     */
    public void setPass(Boolean pass) {
        this.pass = pass;
    }
}