package org.itboys.trade.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WeixinConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    protected int limitStart = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    protected int limitEnd = -1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    public WeixinConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    public void setLimitStart(int limitStart) {
        this.limitStart=limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    public int getLimitStart() {
        return limitStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    public void setLimitEnd(int limitEnd) {
        this.limitEnd=limitEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    public int getLimitEnd() {
        return limitEnd;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                return ;
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                return ;
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                return ;
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andWeixinIdIsNull() {
            addCriterion("weixin_id is null");
            return (Criteria) this;
        }

        public Criteria andWeixinIdIsNotNull() {
            addCriterion("weixin_id is not null");
            return (Criteria) this;
        }

        public Criteria andWeixinIdEqualTo(String value) {
            addCriterion("weixin_id =", value, "weixinId");
            return (Criteria) this;
        }

        public Criteria andWeixinIdNotEqualTo(String value) {
            addCriterion("weixin_id <>", value, "weixinId");
            return (Criteria) this;
        }

        public Criteria andWeixinIdGreaterThan(String value) {
            addCriterion("weixin_id >", value, "weixinId");
            return (Criteria) this;
        }

        public Criteria andWeixinIdGreaterThanOrEqualTo(String value) {
            addCriterion("weixin_id >=", value, "weixinId");
            return (Criteria) this;
        }

        public Criteria andWeixinIdLessThan(String value) {
            addCriterion("weixin_id <", value, "weixinId");
            return (Criteria) this;
        }

        public Criteria andWeixinIdLessThanOrEqualTo(String value) {
            addCriterion("weixin_id <=", value, "weixinId");
            return (Criteria) this;
        }

        public Criteria andWeixinIdLike(String value) {
            addCriterion("weixin_id like", value, "weixinId");
            return (Criteria) this;
        }

        public Criteria andWeixinIdNotLike(String value) {
            addCriterion("weixin_id not like", value, "weixinId");
            return (Criteria) this;
        }

        public Criteria andWeixinIdIn(List<String> values) {
            addCriterion("weixin_id in", values, "weixinId");
            return (Criteria) this;
        }

        public Criteria andWeixinIdNotIn(List<String> values) {
            addCriterion("weixin_id not in", values, "weixinId");
            return (Criteria) this;
        }

        public Criteria andWeixinIdBetween(String value1, String value2) {
            addCriterion("weixin_id between", value1, value2, "weixinId");
            return (Criteria) this;
        }

        public Criteria andWeixinIdNotBetween(String value1, String value2) {
            addCriterion("weixin_id not between", value1, value2, "weixinId");
            return (Criteria) this;
        }

        public Criteria andWeixinNoIsNull() {
            addCriterion("weixin_no is null");
            return (Criteria) this;
        }

        public Criteria andWeixinNoIsNotNull() {
            addCriterion("weixin_no is not null");
            return (Criteria) this;
        }

        public Criteria andWeixinNoEqualTo(String value) {
            addCriterion("weixin_no =", value, "weixinNo");
            return (Criteria) this;
        }

        public Criteria andWeixinNoNotEqualTo(String value) {
            addCriterion("weixin_no <>", value, "weixinNo");
            return (Criteria) this;
        }

        public Criteria andWeixinNoGreaterThan(String value) {
            addCriterion("weixin_no >", value, "weixinNo");
            return (Criteria) this;
        }

        public Criteria andWeixinNoGreaterThanOrEqualTo(String value) {
            addCriterion("weixin_no >=", value, "weixinNo");
            return (Criteria) this;
        }

        public Criteria andWeixinNoLessThan(String value) {
            addCriterion("weixin_no <", value, "weixinNo");
            return (Criteria) this;
        }

        public Criteria andWeixinNoLessThanOrEqualTo(String value) {
            addCriterion("weixin_no <=", value, "weixinNo");
            return (Criteria) this;
        }

        public Criteria andWeixinNoLike(String value) {
            addCriterion("weixin_no like", value, "weixinNo");
            return (Criteria) this;
        }

        public Criteria andWeixinNoNotLike(String value) {
            addCriterion("weixin_no not like", value, "weixinNo");
            return (Criteria) this;
        }

        public Criteria andWeixinNoIn(List<String> values) {
            addCriterion("weixin_no in", values, "weixinNo");
            return (Criteria) this;
        }

        public Criteria andWeixinNoNotIn(List<String> values) {
            addCriterion("weixin_no not in", values, "weixinNo");
            return (Criteria) this;
        }

        public Criteria andWeixinNoBetween(String value1, String value2) {
            addCriterion("weixin_no between", value1, value2, "weixinNo");
            return (Criteria) this;
        }

        public Criteria andWeixinNoNotBetween(String value1, String value2) {
            addCriterion("weixin_no not between", value1, value2, "weixinNo");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Boolean value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Boolean value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Boolean value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Boolean value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Boolean> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Boolean> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andLogoIsNull() {
            addCriterion("logo is null");
            return (Criteria) this;
        }

        public Criteria andLogoIsNotNull() {
            addCriterion("logo is not null");
            return (Criteria) this;
        }

        public Criteria andLogoEqualTo(String value) {
            addCriterion("logo =", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotEqualTo(String value) {
            addCriterion("logo <>", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThan(String value) {
            addCriterion("logo >", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoGreaterThanOrEqualTo(String value) {
            addCriterion("logo >=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThan(String value) {
            addCriterion("logo <", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLessThanOrEqualTo(String value) {
            addCriterion("logo <=", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoLike(String value) {
            addCriterion("logo like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotLike(String value) {
            addCriterion("logo not like", value, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoIn(List<String> values) {
            addCriterion("logo in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotIn(List<String> values) {
            addCriterion("logo not in", values, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoBetween(String value1, String value2) {
            addCriterion("logo between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andLogoNotBetween(String value1, String value2) {
            addCriterion("logo not between", value1, value2, "logo");
            return (Criteria) this;
        }

        public Criteria andEwmIsNull() {
            addCriterion("ewm is null");
            return (Criteria) this;
        }

        public Criteria andEwmIsNotNull() {
            addCriterion("ewm is not null");
            return (Criteria) this;
        }

        public Criteria andEwmEqualTo(String value) {
            addCriterion("ewm =", value, "ewm");
            return (Criteria) this;
        }

        public Criteria andEwmNotEqualTo(String value) {
            addCriterion("ewm <>", value, "ewm");
            return (Criteria) this;
        }

        public Criteria andEwmGreaterThan(String value) {
            addCriterion("ewm >", value, "ewm");
            return (Criteria) this;
        }

        public Criteria andEwmGreaterThanOrEqualTo(String value) {
            addCriterion("ewm >=", value, "ewm");
            return (Criteria) this;
        }

        public Criteria andEwmLessThan(String value) {
            addCriterion("ewm <", value, "ewm");
            return (Criteria) this;
        }

        public Criteria andEwmLessThanOrEqualTo(String value) {
            addCriterion("ewm <=", value, "ewm");
            return (Criteria) this;
        }

        public Criteria andEwmLike(String value) {
            addCriterion("ewm like", value, "ewm");
            return (Criteria) this;
        }

        public Criteria andEwmNotLike(String value) {
            addCriterion("ewm not like", value, "ewm");
            return (Criteria) this;
        }

        public Criteria andEwmIn(List<String> values) {
            addCriterion("ewm in", values, "ewm");
            return (Criteria) this;
        }

        public Criteria andEwmNotIn(List<String> values) {
            addCriterion("ewm not in", values, "ewm");
            return (Criteria) this;
        }

        public Criteria andEwmBetween(String value1, String value2) {
            addCriterion("ewm between", value1, value2, "ewm");
            return (Criteria) this;
        }

        public Criteria andEwmNotBetween(String value1, String value2) {
            addCriterion("ewm not between", value1, value2, "ewm");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("app_id is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("app_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(String value) {
            addCriterion("app_id =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(String value) {
            addCriterion("app_id <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(String value) {
            addCriterion("app_id >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("app_id >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(String value) {
            addCriterion("app_id <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(String value) {
            addCriterion("app_id <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLike(String value) {
            addCriterion("app_id like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotLike(String value) {
            addCriterion("app_id not like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<String> values) {
            addCriterion("app_id in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<String> values) {
            addCriterion("app_id not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(String value1, String value2) {
            addCriterion("app_id between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(String value1, String value2) {
            addCriterion("app_id not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppSecretIsNull() {
            addCriterion("app_secret is null");
            return (Criteria) this;
        }

        public Criteria andAppSecretIsNotNull() {
            addCriterion("app_secret is not null");
            return (Criteria) this;
        }

        public Criteria andAppSecretEqualTo(String value) {
            addCriterion("app_secret =", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretNotEqualTo(String value) {
            addCriterion("app_secret <>", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretGreaterThan(String value) {
            addCriterion("app_secret >", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretGreaterThanOrEqualTo(String value) {
            addCriterion("app_secret >=", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretLessThan(String value) {
            addCriterion("app_secret <", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretLessThanOrEqualTo(String value) {
            addCriterion("app_secret <=", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretLike(String value) {
            addCriterion("app_secret like", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretNotLike(String value) {
            addCriterion("app_secret not like", value, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretIn(List<String> values) {
            addCriterion("app_secret in", values, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretNotIn(List<String> values) {
            addCriterion("app_secret not in", values, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretBetween(String value1, String value2) {
            addCriterion("app_secret between", value1, value2, "appSecret");
            return (Criteria) this;
        }

        public Criteria andAppSecretNotBetween(String value1, String value2) {
            addCriterion("app_secret not between", value1, value2, "appSecret");
            return (Criteria) this;
        }

        public Criteria andTokenIsNull() {
            addCriterion("token is null");
            return (Criteria) this;
        }

        public Criteria andTokenIsNotNull() {
            addCriterion("token is not null");
            return (Criteria) this;
        }

        public Criteria andTokenEqualTo(String value) {
            addCriterion("token =", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotEqualTo(String value) {
            addCriterion("token <>", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThan(String value) {
            addCriterion("token >", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenGreaterThanOrEqualTo(String value) {
            addCriterion("token >=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThan(String value) {
            addCriterion("token <", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLessThanOrEqualTo(String value) {
            addCriterion("token <=", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenLike(String value) {
            addCriterion("token like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotLike(String value) {
            addCriterion("token not like", value, "token");
            return (Criteria) this;
        }

        public Criteria andTokenIn(List<String> values) {
            addCriterion("token in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotIn(List<String> values) {
            addCriterion("token not in", values, "token");
            return (Criteria) this;
        }

        public Criteria andTokenBetween(String value1, String value2) {
            addCriterion("token between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andTokenNotBetween(String value1, String value2) {
            addCriterion("token not between", value1, value2, "token");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(Long value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(Long value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(Long value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(Long value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(Long value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(Long value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<Long> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<Long> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(Long value1, Long value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(Long value1, Long value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNull() {
            addCriterion("updater is null");
            return (Criteria) this;
        }

        public Criteria andUpdaterIsNotNull() {
            addCriterion("updater is not null");
            return (Criteria) this;
        }

        public Criteria andUpdaterEqualTo(Long value) {
            addCriterion("updater =", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotEqualTo(Long value) {
            addCriterion("updater <>", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThan(Long value) {
            addCriterion("updater >", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterGreaterThanOrEqualTo(Long value) {
            addCriterion("updater >=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThan(Long value) {
            addCriterion("updater <", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterLessThanOrEqualTo(Long value) {
            addCriterion("updater <=", value, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterIn(List<Long> values) {
            addCriterion("updater in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotIn(List<Long> values) {
            addCriterion("updater not in", values, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterBetween(Long value1, Long value2) {
            addCriterion("updater between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdaterNotBetween(Long value1, Long value2) {
            addCriterion("updater not between", value1, value2, "updater");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Byte value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Byte value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Byte value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Byte value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Byte value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Byte> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Byte> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Byte value1, Byte value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Byte value1, Byte value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNull() {
            addCriterion("project_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectIdIsNotNull() {
            addCriterion("project_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectIdEqualTo(Long value) {
            addCriterion("project_id =", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotEqualTo(Long value) {
            addCriterion("project_id <>", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThan(Long value) {
            addCriterion("project_id >", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdGreaterThanOrEqualTo(Long value) {
            addCriterion("project_id >=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThan(Long value) {
            addCriterion("project_id <", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdLessThanOrEqualTo(Long value) {
            addCriterion("project_id <=", value, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdIn(List<Long> values) {
            addCriterion("project_id in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotIn(List<Long> values) {
            addCriterion("project_id not in", values, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdBetween(Long value1, Long value2) {
            addCriterion("project_id between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andProjectIdNotBetween(Long value1, Long value2) {
            addCriterion("project_id not between", value1, value2, "projectId");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(Long value) {
            addCriterion("parent_id =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(Long value) {
            addCriterion("parent_id <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(Long value) {
            addCriterion("parent_id >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("parent_id >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(Long value) {
            addCriterion("parent_id <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(Long value) {
            addCriterion("parent_id <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<Long> values) {
            addCriterion("parent_id in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<Long> values) {
            addCriterion("parent_id not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(Long value1, Long value2) {
            addCriterion("parent_id between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(Long value1, Long value2) {
            addCriterion("parent_id not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andPartnerKeyIsNull() {
            addCriterion("partner_key is null");
            return (Criteria) this;
        }

        public Criteria andPartnerKeyIsNotNull() {
            addCriterion("partner_key is not null");
            return (Criteria) this;
        }

        public Criteria andPartnerKeyEqualTo(String value) {
            addCriterion("partner_key =", value, "partnerKey");
            return (Criteria) this;
        }

        public Criteria andPartnerKeyNotEqualTo(String value) {
            addCriterion("partner_key <>", value, "partnerKey");
            return (Criteria) this;
        }

        public Criteria andPartnerKeyGreaterThan(String value) {
            addCriterion("partner_key >", value, "partnerKey");
            return (Criteria) this;
        }

        public Criteria andPartnerKeyGreaterThanOrEqualTo(String value) {
            addCriterion("partner_key >=", value, "partnerKey");
            return (Criteria) this;
        }

        public Criteria andPartnerKeyLessThan(String value) {
            addCriterion("partner_key <", value, "partnerKey");
            return (Criteria) this;
        }

        public Criteria andPartnerKeyLessThanOrEqualTo(String value) {
            addCriterion("partner_key <=", value, "partnerKey");
            return (Criteria) this;
        }

        public Criteria andPartnerKeyLike(String value) {
            addCriterion("partner_key like", value, "partnerKey");
            return (Criteria) this;
        }

        public Criteria andPartnerKeyNotLike(String value) {
            addCriterion("partner_key not like", value, "partnerKey");
            return (Criteria) this;
        }

        public Criteria andPartnerKeyIn(List<String> values) {
            addCriterion("partner_key in", values, "partnerKey");
            return (Criteria) this;
        }

        public Criteria andPartnerKeyNotIn(List<String> values) {
            addCriterion("partner_key not in", values, "partnerKey");
            return (Criteria) this;
        }

        public Criteria andPartnerKeyBetween(String value1, String value2) {
            addCriterion("partner_key between", value1, value2, "partnerKey");
            return (Criteria) this;
        }

        public Criteria andPartnerKeyNotBetween(String value1, String value2) {
            addCriterion("partner_key not between", value1, value2, "partnerKey");
            return (Criteria) this;
        }

        public Criteria andSiteDomainIsNull() {
            addCriterion("site_domain is null");
            return (Criteria) this;
        }

        public Criteria andSiteDomainIsNotNull() {
            addCriterion("site_domain is not null");
            return (Criteria) this;
        }

        public Criteria andSiteDomainEqualTo(String value) {
            addCriterion("site_domain =", value, "siteDomain");
            return (Criteria) this;
        }

        public Criteria andSiteDomainNotEqualTo(String value) {
            addCriterion("site_domain <>", value, "siteDomain");
            return (Criteria) this;
        }

        public Criteria andSiteDomainGreaterThan(String value) {
            addCriterion("site_domain >", value, "siteDomain");
            return (Criteria) this;
        }

        public Criteria andSiteDomainGreaterThanOrEqualTo(String value) {
            addCriterion("site_domain >=", value, "siteDomain");
            return (Criteria) this;
        }

        public Criteria andSiteDomainLessThan(String value) {
            addCriterion("site_domain <", value, "siteDomain");
            return (Criteria) this;
        }

        public Criteria andSiteDomainLessThanOrEqualTo(String value) {
            addCriterion("site_domain <=", value, "siteDomain");
            return (Criteria) this;
        }

        public Criteria andSiteDomainLike(String value) {
            addCriterion("site_domain like", value, "siteDomain");
            return (Criteria) this;
        }

        public Criteria andSiteDomainNotLike(String value) {
            addCriterion("site_domain not like", value, "siteDomain");
            return (Criteria) this;
        }

        public Criteria andSiteDomainIn(List<String> values) {
            addCriterion("site_domain in", values, "siteDomain");
            return (Criteria) this;
        }

        public Criteria andSiteDomainNotIn(List<String> values) {
            addCriterion("site_domain not in", values, "siteDomain");
            return (Criteria) this;
        }

        public Criteria andSiteDomainBetween(String value1, String value2) {
            addCriterion("site_domain between", value1, value2, "siteDomain");
            return (Criteria) this;
        }

        public Criteria andSiteDomainNotBetween(String value1, String value2) {
            addCriterion("site_domain not between", value1, value2, "siteDomain");
            return (Criteria) this;
        }

        public Criteria andReflectBeanIsNull() {
            addCriterion("reflect_bean is null");
            return (Criteria) this;
        }

        public Criteria andReflectBeanIsNotNull() {
            addCriterion("reflect_bean is not null");
            return (Criteria) this;
        }

        public Criteria andReflectBeanEqualTo(String value) {
            addCriterion("reflect_bean =", value, "reflectBean");
            return (Criteria) this;
        }

        public Criteria andReflectBeanNotEqualTo(String value) {
            addCriterion("reflect_bean <>", value, "reflectBean");
            return (Criteria) this;
        }

        public Criteria andReflectBeanGreaterThan(String value) {
            addCriterion("reflect_bean >", value, "reflectBean");
            return (Criteria) this;
        }

        public Criteria andReflectBeanGreaterThanOrEqualTo(String value) {
            addCriterion("reflect_bean >=", value, "reflectBean");
            return (Criteria) this;
        }

        public Criteria andReflectBeanLessThan(String value) {
            addCriterion("reflect_bean <", value, "reflectBean");
            return (Criteria) this;
        }

        public Criteria andReflectBeanLessThanOrEqualTo(String value) {
            addCriterion("reflect_bean <=", value, "reflectBean");
            return (Criteria) this;
        }

        public Criteria andReflectBeanLike(String value) {
            addCriterion("reflect_bean like", value, "reflectBean");
            return (Criteria) this;
        }

        public Criteria andReflectBeanNotLike(String value) {
            addCriterion("reflect_bean not like", value, "reflectBean");
            return (Criteria) this;
        }

        public Criteria andReflectBeanIn(List<String> values) {
            addCriterion("reflect_bean in", values, "reflectBean");
            return (Criteria) this;
        }

        public Criteria andReflectBeanNotIn(List<String> values) {
            addCriterion("reflect_bean not in", values, "reflectBean");
            return (Criteria) this;
        }

        public Criteria andReflectBeanBetween(String value1, String value2) {
            addCriterion("reflect_bean between", value1, value2, "reflectBean");
            return (Criteria) this;
        }

        public Criteria andReflectBeanNotBetween(String value1, String value2) {
            addCriterion("reflect_bean not between", value1, value2, "reflectBean");
            return (Criteria) this;
        }

        public Criteria andReflectMethodIsNull() {
            addCriterion("reflect_method is null");
            return (Criteria) this;
        }

        public Criteria andReflectMethodIsNotNull() {
            addCriterion("reflect_method is not null");
            return (Criteria) this;
        }

        public Criteria andReflectMethodEqualTo(String value) {
            addCriterion("reflect_method =", value, "reflectMethod");
            return (Criteria) this;
        }

        public Criteria andReflectMethodNotEqualTo(String value) {
            addCriterion("reflect_method <>", value, "reflectMethod");
            return (Criteria) this;
        }

        public Criteria andReflectMethodGreaterThan(String value) {
            addCriterion("reflect_method >", value, "reflectMethod");
            return (Criteria) this;
        }

        public Criteria andReflectMethodGreaterThanOrEqualTo(String value) {
            addCriterion("reflect_method >=", value, "reflectMethod");
            return (Criteria) this;
        }

        public Criteria andReflectMethodLessThan(String value) {
            addCriterion("reflect_method <", value, "reflectMethod");
            return (Criteria) this;
        }

        public Criteria andReflectMethodLessThanOrEqualTo(String value) {
            addCriterion("reflect_method <=", value, "reflectMethod");
            return (Criteria) this;
        }

        public Criteria andReflectMethodLike(String value) {
            addCriterion("reflect_method like", value, "reflectMethod");
            return (Criteria) this;
        }

        public Criteria andReflectMethodNotLike(String value) {
            addCriterion("reflect_method not like", value, "reflectMethod");
            return (Criteria) this;
        }

        public Criteria andReflectMethodIn(List<String> values) {
            addCriterion("reflect_method in", values, "reflectMethod");
            return (Criteria) this;
        }

        public Criteria andReflectMethodNotIn(List<String> values) {
            addCriterion("reflect_method not in", values, "reflectMethod");
            return (Criteria) this;
        }

        public Criteria andReflectMethodBetween(String value1, String value2) {
            addCriterion("reflect_method between", value1, value2, "reflectMethod");
            return (Criteria) this;
        }

        public Criteria andReflectMethodNotBetween(String value1, String value2) {
            addCriterion("reflect_method not between", value1, value2, "reflectMethod");
            return (Criteria) this;
        }

        public Criteria andEwm1IsNull() {
            addCriterion("ewm1 is null");
            return (Criteria) this;
        }

        public Criteria andEwm1IsNotNull() {
            addCriterion("ewm1 is not null");
            return (Criteria) this;
        }

        public Criteria andEwm1EqualTo(String value) {
            addCriterion("ewm1 =", value, "ewm1");
            return (Criteria) this;
        }

        public Criteria andEwm1NotEqualTo(String value) {
            addCriterion("ewm1 <>", value, "ewm1");
            return (Criteria) this;
        }

        public Criteria andEwm1GreaterThan(String value) {
            addCriterion("ewm1 >", value, "ewm1");
            return (Criteria) this;
        }

        public Criteria andEwm1GreaterThanOrEqualTo(String value) {
            addCriterion("ewm1 >=", value, "ewm1");
            return (Criteria) this;
        }

        public Criteria andEwm1LessThan(String value) {
            addCriterion("ewm1 <", value, "ewm1");
            return (Criteria) this;
        }

        public Criteria andEwm1LessThanOrEqualTo(String value) {
            addCriterion("ewm1 <=", value, "ewm1");
            return (Criteria) this;
        }

        public Criteria andEwm1Like(String value) {
            addCriterion("ewm1 like", value, "ewm1");
            return (Criteria) this;
        }

        public Criteria andEwm1NotLike(String value) {
            addCriterion("ewm1 not like", value, "ewm1");
            return (Criteria) this;
        }

        public Criteria andEwm1In(List<String> values) {
            addCriterion("ewm1 in", values, "ewm1");
            return (Criteria) this;
        }

        public Criteria andEwm1NotIn(List<String> values) {
            addCriterion("ewm1 not in", values, "ewm1");
            return (Criteria) this;
        }

        public Criteria andEwm1Between(String value1, String value2) {
            addCriterion("ewm1 between", value1, value2, "ewm1");
            return (Criteria) this;
        }

        public Criteria andEwm1NotBetween(String value1, String value2) {
            addCriterion("ewm1 not between", value1, value2, "ewm1");
            return (Criteria) this;
        }

        public Criteria andEwm2IsNull() {
            addCriterion("ewm2 is null");
            return (Criteria) this;
        }

        public Criteria andEwm2IsNotNull() {
            addCriterion("ewm2 is not null");
            return (Criteria) this;
        }

        public Criteria andEwm2EqualTo(String value) {
            addCriterion("ewm2 =", value, "ewm2");
            return (Criteria) this;
        }

        public Criteria andEwm2NotEqualTo(String value) {
            addCriterion("ewm2 <>", value, "ewm2");
            return (Criteria) this;
        }

        public Criteria andEwm2GreaterThan(String value) {
            addCriterion("ewm2 >", value, "ewm2");
            return (Criteria) this;
        }

        public Criteria andEwm2GreaterThanOrEqualTo(String value) {
            addCriterion("ewm2 >=", value, "ewm2");
            return (Criteria) this;
        }

        public Criteria andEwm2LessThan(String value) {
            addCriterion("ewm2 <", value, "ewm2");
            return (Criteria) this;
        }

        public Criteria andEwm2LessThanOrEqualTo(String value) {
            addCriterion("ewm2 <=", value, "ewm2");
            return (Criteria) this;
        }

        public Criteria andEwm2Like(String value) {
            addCriterion("ewm2 like", value, "ewm2");
            return (Criteria) this;
        }

        public Criteria andEwm2NotLike(String value) {
            addCriterion("ewm2 not like", value, "ewm2");
            return (Criteria) this;
        }

        public Criteria andEwm2In(List<String> values) {
            addCriterion("ewm2 in", values, "ewm2");
            return (Criteria) this;
        }

        public Criteria andEwm2NotIn(List<String> values) {
            addCriterion("ewm2 not in", values, "ewm2");
            return (Criteria) this;
        }

        public Criteria andEwm2Between(String value1, String value2) {
            addCriterion("ewm2 between", value1, value2, "ewm2");
            return (Criteria) this;
        }

        public Criteria andEwm2NotBetween(String value1, String value2) {
            addCriterion("ewm2 not between", value1, value2, "ewm2");
            return (Criteria) this;
        }

        public Criteria andEwm3IsNull() {
            addCriterion("ewm3 is null");
            return (Criteria) this;
        }

        public Criteria andEwm3IsNotNull() {
            addCriterion("ewm3 is not null");
            return (Criteria) this;
        }

        public Criteria andEwm3EqualTo(String value) {
            addCriterion("ewm3 =", value, "ewm3");
            return (Criteria) this;
        }

        public Criteria andEwm3NotEqualTo(String value) {
            addCriterion("ewm3 <>", value, "ewm3");
            return (Criteria) this;
        }

        public Criteria andEwm3GreaterThan(String value) {
            addCriterion("ewm3 >", value, "ewm3");
            return (Criteria) this;
        }

        public Criteria andEwm3GreaterThanOrEqualTo(String value) {
            addCriterion("ewm3 >=", value, "ewm3");
            return (Criteria) this;
        }

        public Criteria andEwm3LessThan(String value) {
            addCriterion("ewm3 <", value, "ewm3");
            return (Criteria) this;
        }

        public Criteria andEwm3LessThanOrEqualTo(String value) {
            addCriterion("ewm3 <=", value, "ewm3");
            return (Criteria) this;
        }

        public Criteria andEwm3Like(String value) {
            addCriterion("ewm3 like", value, "ewm3");
            return (Criteria) this;
        }

        public Criteria andEwm3NotLike(String value) {
            addCriterion("ewm3 not like", value, "ewm3");
            return (Criteria) this;
        }

        public Criteria andEwm3In(List<String> values) {
            addCriterion("ewm3 in", values, "ewm3");
            return (Criteria) this;
        }

        public Criteria andEwm3NotIn(List<String> values) {
            addCriterion("ewm3 not in", values, "ewm3");
            return (Criteria) this;
        }

        public Criteria andEwm3Between(String value1, String value2) {
            addCriterion("ewm3 between", value1, value2, "ewm3");
            return (Criteria) this;
        }

        public Criteria andEwm3NotBetween(String value1, String value2) {
            addCriterion("ewm3 not between", value1, value2, "ewm3");
            return (Criteria) this;
        }

        public Criteria andEwm4IsNull() {
            addCriterion("ewm4 is null");
            return (Criteria) this;
        }

        public Criteria andEwm4IsNotNull() {
            addCriterion("ewm4 is not null");
            return (Criteria) this;
        }

        public Criteria andEwm4EqualTo(String value) {
            addCriterion("ewm4 =", value, "ewm4");
            return (Criteria) this;
        }

        public Criteria andEwm4NotEqualTo(String value) {
            addCriterion("ewm4 <>", value, "ewm4");
            return (Criteria) this;
        }

        public Criteria andEwm4GreaterThan(String value) {
            addCriterion("ewm4 >", value, "ewm4");
            return (Criteria) this;
        }

        public Criteria andEwm4GreaterThanOrEqualTo(String value) {
            addCriterion("ewm4 >=", value, "ewm4");
            return (Criteria) this;
        }

        public Criteria andEwm4LessThan(String value) {
            addCriterion("ewm4 <", value, "ewm4");
            return (Criteria) this;
        }

        public Criteria andEwm4LessThanOrEqualTo(String value) {
            addCriterion("ewm4 <=", value, "ewm4");
            return (Criteria) this;
        }

        public Criteria andEwm4Like(String value) {
            addCriterion("ewm4 like", value, "ewm4");
            return (Criteria) this;
        }

        public Criteria andEwm4NotLike(String value) {
            addCriterion("ewm4 not like", value, "ewm4");
            return (Criteria) this;
        }

        public Criteria andEwm4In(List<String> values) {
            addCriterion("ewm4 in", values, "ewm4");
            return (Criteria) this;
        }

        public Criteria andEwm4NotIn(List<String> values) {
            addCriterion("ewm4 not in", values, "ewm4");
            return (Criteria) this;
        }

        public Criteria andEwm4Between(String value1, String value2) {
            addCriterion("ewm4 between", value1, value2, "ewm4");
            return (Criteria) this;
        }

        public Criteria andEwm4NotBetween(String value1, String value2) {
            addCriterion("ewm4 not between", value1, value2, "ewm4");
            return (Criteria) this;
        }

        public Criteria andEwm5IsNull() {
            addCriterion("ewm5 is null");
            return (Criteria) this;
        }

        public Criteria andEwm5IsNotNull() {
            addCriterion("ewm5 is not null");
            return (Criteria) this;
        }

        public Criteria andEwm5EqualTo(String value) {
            addCriterion("ewm5 =", value, "ewm5");
            return (Criteria) this;
        }

        public Criteria andEwm5NotEqualTo(String value) {
            addCriterion("ewm5 <>", value, "ewm5");
            return (Criteria) this;
        }

        public Criteria andEwm5GreaterThan(String value) {
            addCriterion("ewm5 >", value, "ewm5");
            return (Criteria) this;
        }

        public Criteria andEwm5GreaterThanOrEqualTo(String value) {
            addCriterion("ewm5 >=", value, "ewm5");
            return (Criteria) this;
        }

        public Criteria andEwm5LessThan(String value) {
            addCriterion("ewm5 <", value, "ewm5");
            return (Criteria) this;
        }

        public Criteria andEwm5LessThanOrEqualTo(String value) {
            addCriterion("ewm5 <=", value, "ewm5");
            return (Criteria) this;
        }

        public Criteria andEwm5Like(String value) {
            addCriterion("ewm5 like", value, "ewm5");
            return (Criteria) this;
        }

        public Criteria andEwm5NotLike(String value) {
            addCriterion("ewm5 not like", value, "ewm5");
            return (Criteria) this;
        }

        public Criteria andEwm5In(List<String> values) {
            addCriterion("ewm5 in", values, "ewm5");
            return (Criteria) this;
        }

        public Criteria andEwm5NotIn(List<String> values) {
            addCriterion("ewm5 not in", values, "ewm5");
            return (Criteria) this;
        }

        public Criteria andEwm5Between(String value1, String value2) {
            addCriterion("ewm5 between", value1, value2, "ewm5");
            return (Criteria) this;
        }

        public Criteria andEwm5NotBetween(String value1, String value2) {
            addCriterion("ewm5 not between", value1, value2, "ewm5");
            return (Criteria) this;
        }

        public Criteria andPaySignKeyIsNull() {
            addCriterion("pay_sign_key is null");
            return (Criteria) this;
        }

        public Criteria andPaySignKeyIsNotNull() {
            addCriterion("pay_sign_key is not null");
            return (Criteria) this;
        }

        public Criteria andPaySignKeyEqualTo(String value) {
            addCriterion("pay_sign_key =", value, "paySignKey");
            return (Criteria) this;
        }

        public Criteria andPaySignKeyNotEqualTo(String value) {
            addCriterion("pay_sign_key <>", value, "paySignKey");
            return (Criteria) this;
        }

        public Criteria andPaySignKeyGreaterThan(String value) {
            addCriterion("pay_sign_key >", value, "paySignKey");
            return (Criteria) this;
        }

        public Criteria andPaySignKeyGreaterThanOrEqualTo(String value) {
            addCriterion("pay_sign_key >=", value, "paySignKey");
            return (Criteria) this;
        }

        public Criteria andPaySignKeyLessThan(String value) {
            addCriterion("pay_sign_key <", value, "paySignKey");
            return (Criteria) this;
        }

        public Criteria andPaySignKeyLessThanOrEqualTo(String value) {
            addCriterion("pay_sign_key <=", value, "paySignKey");
            return (Criteria) this;
        }

        public Criteria andPaySignKeyLike(String value) {
            addCriterion("pay_sign_key like", value, "paySignKey");
            return (Criteria) this;
        }

        public Criteria andPaySignKeyNotLike(String value) {
            addCriterion("pay_sign_key not like", value, "paySignKey");
            return (Criteria) this;
        }

        public Criteria andPaySignKeyIn(List<String> values) {
            addCriterion("pay_sign_key in", values, "paySignKey");
            return (Criteria) this;
        }

        public Criteria andPaySignKeyNotIn(List<String> values) {
            addCriterion("pay_sign_key not in", values, "paySignKey");
            return (Criteria) this;
        }

        public Criteria andPaySignKeyBetween(String value1, String value2) {
            addCriterion("pay_sign_key between", value1, value2, "paySignKey");
            return (Criteria) this;
        }

        public Criteria andPaySignKeyNotBetween(String value1, String value2) {
            addCriterion("pay_sign_key not between", value1, value2, "paySignKey");
            return (Criteria) this;
        }

        public Criteria andPartnerIdIsNull() {
            addCriterion("partner_id is null");
            return (Criteria) this;
        }

        public Criteria andPartnerIdIsNotNull() {
            addCriterion("partner_id is not null");
            return (Criteria) this;
        }

        public Criteria andPartnerIdEqualTo(String value) {
            addCriterion("partner_id =", value, "partnerId");
            return (Criteria) this;
        }

        public Criteria andPartnerIdNotEqualTo(String value) {
            addCriterion("partner_id <>", value, "partnerId");
            return (Criteria) this;
        }

        public Criteria andPartnerIdGreaterThan(String value) {
            addCriterion("partner_id >", value, "partnerId");
            return (Criteria) this;
        }

        public Criteria andPartnerIdGreaterThanOrEqualTo(String value) {
            addCriterion("partner_id >=", value, "partnerId");
            return (Criteria) this;
        }

        public Criteria andPartnerIdLessThan(String value) {
            addCriterion("partner_id <", value, "partnerId");
            return (Criteria) this;
        }

        public Criteria andPartnerIdLessThanOrEqualTo(String value) {
            addCriterion("partner_id <=", value, "partnerId");
            return (Criteria) this;
        }

        public Criteria andPartnerIdLike(String value) {
            addCriterion("partner_id like", value, "partnerId");
            return (Criteria) this;
        }

        public Criteria andPartnerIdNotLike(String value) {
            addCriterion("partner_id not like", value, "partnerId");
            return (Criteria) this;
        }

        public Criteria andPartnerIdIn(List<String> values) {
            addCriterion("partner_id in", values, "partnerId");
            return (Criteria) this;
        }

        public Criteria andPartnerIdNotIn(List<String> values) {
            addCriterion("partner_id not in", values, "partnerId");
            return (Criteria) this;
        }

        public Criteria andPartnerIdBetween(String value1, String value2) {
            addCriterion("partner_id between", value1, value2, "partnerId");
            return (Criteria) this;
        }

        public Criteria andPartnerIdNotBetween(String value1, String value2) {
            addCriterion("partner_id not between", value1, value2, "partnerId");
            return (Criteria) this;
        }

        public Criteria andField1IsNull() {
            addCriterion("field1 is null");
            return (Criteria) this;
        }

        public Criteria andField1IsNotNull() {
            addCriterion("field1 is not null");
            return (Criteria) this;
        }

        public Criteria andField1EqualTo(String value) {
            addCriterion("field1 =", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1NotEqualTo(String value) {
            addCriterion("field1 <>", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1GreaterThan(String value) {
            addCriterion("field1 >", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1GreaterThanOrEqualTo(String value) {
            addCriterion("field1 >=", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1LessThan(String value) {
            addCriterion("field1 <", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1LessThanOrEqualTo(String value) {
            addCriterion("field1 <=", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1Like(String value) {
            addCriterion("field1 like", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1NotLike(String value) {
            addCriterion("field1 not like", value, "field1");
            return (Criteria) this;
        }

        public Criteria andField1In(List<String> values) {
            addCriterion("field1 in", values, "field1");
            return (Criteria) this;
        }

        public Criteria andField1NotIn(List<String> values) {
            addCriterion("field1 not in", values, "field1");
            return (Criteria) this;
        }

        public Criteria andField1Between(String value1, String value2) {
            addCriterion("field1 between", value1, value2, "field1");
            return (Criteria) this;
        }

        public Criteria andField1NotBetween(String value1, String value2) {
            addCriterion("field1 not between", value1, value2, "field1");
            return (Criteria) this;
        }

        public Criteria andField2IsNull() {
            addCriterion("field2 is null");
            return (Criteria) this;
        }

        public Criteria andField2IsNotNull() {
            addCriterion("field2 is not null");
            return (Criteria) this;
        }

        public Criteria andField2EqualTo(String value) {
            addCriterion("field2 =", value, "field2");
            return (Criteria) this;
        }

        public Criteria andField2NotEqualTo(String value) {
            addCriterion("field2 <>", value, "field2");
            return (Criteria) this;
        }

        public Criteria andField2GreaterThan(String value) {
            addCriterion("field2 >", value, "field2");
            return (Criteria) this;
        }

        public Criteria andField2GreaterThanOrEqualTo(String value) {
            addCriterion("field2 >=", value, "field2");
            return (Criteria) this;
        }

        public Criteria andField2LessThan(String value) {
            addCriterion("field2 <", value, "field2");
            return (Criteria) this;
        }

        public Criteria andField2LessThanOrEqualTo(String value) {
            addCriterion("field2 <=", value, "field2");
            return (Criteria) this;
        }

        public Criteria andField2Like(String value) {
            addCriterion("field2 like", value, "field2");
            return (Criteria) this;
        }

        public Criteria andField2NotLike(String value) {
            addCriterion("field2 not like", value, "field2");
            return (Criteria) this;
        }

        public Criteria andField2In(List<String> values) {
            addCriterion("field2 in", values, "field2");
            return (Criteria) this;
        }

        public Criteria andField2NotIn(List<String> values) {
            addCriterion("field2 not in", values, "field2");
            return (Criteria) this;
        }

        public Criteria andField2Between(String value1, String value2) {
            addCriterion("field2 between", value1, value2, "field2");
            return (Criteria) this;
        }

        public Criteria andField2NotBetween(String value1, String value2) {
            addCriterion("field2 not between", value1, value2, "field2");
            return (Criteria) this;
        }

        public Criteria andField3IsNull() {
            addCriterion("field3 is null");
            return (Criteria) this;
        }

        public Criteria andField3IsNotNull() {
            addCriterion("field3 is not null");
            return (Criteria) this;
        }

        public Criteria andField3EqualTo(String value) {
            addCriterion("field3 =", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3NotEqualTo(String value) {
            addCriterion("field3 <>", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3GreaterThan(String value) {
            addCriterion("field3 >", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3GreaterThanOrEqualTo(String value) {
            addCriterion("field3 >=", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3LessThan(String value) {
            addCriterion("field3 <", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3LessThanOrEqualTo(String value) {
            addCriterion("field3 <=", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3Like(String value) {
            addCriterion("field3 like", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3NotLike(String value) {
            addCriterion("field3 not like", value, "field3");
            return (Criteria) this;
        }

        public Criteria andField3In(List<String> values) {
            addCriterion("field3 in", values, "field3");
            return (Criteria) this;
        }

        public Criteria andField3NotIn(List<String> values) {
            addCriterion("field3 not in", values, "field3");
            return (Criteria) this;
        }

        public Criteria andField3Between(String value1, String value2) {
            addCriterion("field3 between", value1, value2, "field3");
            return (Criteria) this;
        }

        public Criteria andField3NotBetween(String value1, String value2) {
            addCriterion("field3 not between", value1, value2, "field3");
            return (Criteria) this;
        }

        public Criteria andObjIdIsNull() {
            addCriterion("obj_id is null");
            return (Criteria) this;
        }

        public Criteria andObjIdIsNotNull() {
            addCriterion("obj_id is not null");
            return (Criteria) this;
        }

        public Criteria andObjIdEqualTo(Long value) {
            addCriterion("obj_id =", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdNotEqualTo(Long value) {
            addCriterion("obj_id <>", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdGreaterThan(Long value) {
            addCriterion("obj_id >", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdGreaterThanOrEqualTo(Long value) {
            addCriterion("obj_id >=", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdLessThan(Long value) {
            addCriterion("obj_id <", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdLessThanOrEqualTo(Long value) {
            addCriterion("obj_id <=", value, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdIn(List<Long> values) {
            addCriterion("obj_id in", values, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdNotIn(List<Long> values) {
            addCriterion("obj_id not in", values, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdBetween(Long value1, Long value2) {
            addCriterion("obj_id between", value1, value2, "objId");
            return (Criteria) this;
        }

        public Criteria andObjIdNotBetween(Long value1, Long value2) {
            addCriterion("obj_id not between", value1, value2, "objId");
            return (Criteria) this;
        }

        public Criteria andObjId1IsNull() {
            addCriterion("obj_id1 is null");
            return (Criteria) this;
        }

        public Criteria andObjId1IsNotNull() {
            addCriterion("obj_id1 is not null");
            return (Criteria) this;
        }

        public Criteria andObjId1EqualTo(Long value) {
            addCriterion("obj_id1 =", value, "objId1");
            return (Criteria) this;
        }

        public Criteria andObjId1NotEqualTo(Long value) {
            addCriterion("obj_id1 <>", value, "objId1");
            return (Criteria) this;
        }

        public Criteria andObjId1GreaterThan(Long value) {
            addCriterion("obj_id1 >", value, "objId1");
            return (Criteria) this;
        }

        public Criteria andObjId1GreaterThanOrEqualTo(Long value) {
            addCriterion("obj_id1 >=", value, "objId1");
            return (Criteria) this;
        }

        public Criteria andObjId1LessThan(Long value) {
            addCriterion("obj_id1 <", value, "objId1");
            return (Criteria) this;
        }

        public Criteria andObjId1LessThanOrEqualTo(Long value) {
            addCriterion("obj_id1 <=", value, "objId1");
            return (Criteria) this;
        }

        public Criteria andObjId1In(List<Long> values) {
            addCriterion("obj_id1 in", values, "objId1");
            return (Criteria) this;
        }

        public Criteria andObjId1NotIn(List<Long> values) {
            addCriterion("obj_id1 not in", values, "objId1");
            return (Criteria) this;
        }

        public Criteria andObjId1Between(Long value1, Long value2) {
            addCriterion("obj_id1 between", value1, value2, "objId1");
            return (Criteria) this;
        }

        public Criteria andObjId1NotBetween(Long value1, Long value2) {
            addCriterion("obj_id1 not between", value1, value2, "objId1");
            return (Criteria) this;
        }

        public Criteria andPassIsNull() {
            addCriterion("pass is null");
            return (Criteria) this;
        }

        public Criteria andPassIsNotNull() {
            addCriterion("pass is not null");
            return (Criteria) this;
        }

        public Criteria andPassEqualTo(Boolean value) {
            addCriterion("pass =", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassNotEqualTo(Boolean value) {
            addCriterion("pass <>", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassGreaterThan(Boolean value) {
            addCriterion("pass >", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassGreaterThanOrEqualTo(Boolean value) {
            addCriterion("pass >=", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassLessThan(Boolean value) {
            addCriterion("pass <", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassLessThanOrEqualTo(Boolean value) {
            addCriterion("pass <=", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassIn(List<Boolean> values) {
            addCriterion("pass in", values, "pass");
            return (Criteria) this;
        }

        public Criteria andPassNotIn(List<Boolean> values) {
            addCriterion("pass not in", values, "pass");
            return (Criteria) this;
        }

        public Criteria andPassBetween(Boolean value1, Boolean value2) {
            addCriterion("pass between", value1, value2, "pass");
            return (Criteria) this;
        }

        public Criteria andPassNotBetween(Boolean value1, Boolean value2) {
            addCriterion("pass not between", value1, value2, "pass");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weixin_config
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weixin_config
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}